### ISSUE TITLE
Power operator displays in a wrong way

### ISSUE THREAD

**Issue by labulaka521** [jdneo/vscode-leetcode#74] opened 2018-11-09 09:39 UTC
![](https://ws1.sinaimg.cn/large/005Oh4GZly1fx1y99qxiij31a004sq40.jpg)
![](https://ws1.sinaimg.cn/large/005Oh4GZly1fx1y99r9v7j30s405u0tj.jpg)
pow will change
i think you could instend `^`

**Comment by jdneo** [comment] 2018-11-09 10:02
This might be caused by the leetcode-cli, the text is wrongly parsed.

**Comment by labulaka521** [comment] 2018-11-09 13:53
oh..thanks you, but fortunately, it has little effect on me

**Comment by jdneo** [comment] 2018-12-22 08:35
Trying to send a [PR](https://github.com/skygragon/leetcode-cli/pull/144) to fix this...

**Comment by labulaka521** [comment] 2018-12-25 05:18
thanks you very much

**Comment by jdneo** [comment] 2019-02-09 13:07
PR gets merged, waiting for the new CLI get released...

**Closed** 2019-03-03 11:09 UTC
Labels: bug, external dependency
