### ISSUE TITLE
Cannot sign in using a password generated by KeePass

### ISSUE THREAD

**Issue by AB1908** [jdneo/vscode-leetcode#304] opened 2019-05-03 20:46 UTC
## 🐛 Bug Report
I use KeePass to generate and manage all my passwords. My password is a randomly generated string containing special characters of length 12. I have verified that I am able to sign in via Firefox and Chrome, but not via the Leetcode extension. I followed the steps in the FAQ to no avail.

## To Reproduce

1. Generate a random password using any decent password generator which also must contain special characters like #$%^*(.
2. Try to sign in via the extension

## Expected behavior

I expected to be able to sign in.

## Extension Output
```
v10.15.2
 Active  Name               Version         Desc
----------------------------------------------------------------------------------------------------
   ✘     solution.discuss   2019.02.03      Plugin to fetch most voted solution in discussions.
   ✔     company            2017.12.18      Plugin to query by company for free user.
   ✔     cache              default         Plugin to provide local cache.
   ✔     retry              default         Plugin to retry last failed request if autologin.enable is on.
   ✘     leetcode.cn        2018.11.25      Plugin to talk with leetcode-cn APIs.
   ✔     leetcode           default         Plugin to talk with leetcode APIs.
 Active  Name               Version         Desc
----------------------------------------------------------------------------------------------------
   ✔     solution.discuss   2019.02.03      Plugin to fetch most voted solution in discussions.
   ✔     company            2017.12.18      Plugin to query by company for free user.
   ✔     cache              default         Plugin to provide local cache.
   ✔     retry              default         Plugin to retry last failed request if autologin.enable is on.
   ✘     leetcode.cn        2018.11.25      Plugin to talk with leetcode-cn APIs.
   ✔     leetcode           default         Plugin to talk with leetcode APIs.
 Active  Name               Version         Desc
----------------------------------------------------------------------------------------------------
   ✔     solution.discuss   2019.02.03      Plugin to fetch most voted solution in discussions.
   ✔     company            2017.12.18      Plugin to query by company for free user.
   ✔     cache              default         Plugin to provide local cache.
   ✔     retry              default         Plugin to retry last failed request if autologin.enable is on.
   ✔     leetcode.cn        2018.11.25      Plugin to talk with leetcode-cn APIs.
   ✔     leetcode           default         Plugin to talk with leetcode APIs.
 Active  Name               Version         Desc
----------------------------------------------------------------------------------------------------
   ✔     solution.discuss   2019.02.03      Plugin to fetch most voted solution in discussions.
   ✔     company            2017.12.18      Plugin to query by company for free user.
   ✔     cache              default         Plugin to provide local cache.
   ✔     retry              default         Plugin to retry last failed request if autologin.enable is on.
   ✘     leetcode.cn        2018.11.25      Plugin to talk with leetcode-cn APIs.
   ✔     leetcode           default         Plugin to talk with leetcode APIs.
login: [ERROR] You are not login yet?
pass: login: pass: - Signing in leetcode.com
[ERROR] invalid password?
login: pass: - Signing in leetcode.com
[ERROR] invalid password?
login: pass: - Signing in leetcode.com
[ERROR] invalid password?
login: pass: login: pass: login: pass: login: pass: - Signing in leetcode.com
[ERROR] invalid password?
 Active  Name               Version         Desc
----------------------------------------------------------------------------------------------------
   ✔     solution.discuss   2019.02.03      Plugin to fetch most voted solution in discussions.
   ✔     company            2017.12.18      Plugin to query by company for free user.
   ✔     cache              default         Plugin to provide local cache.
   ✔     retry              default         Plugin to retry last failed request if autologin.enable is on.
   ✔     leetcode.cn        2018.11.25      Plugin to talk with leetcode-cn APIs.
   ✔     leetcode           default         Plugin to talk with leetcode APIs.
[ERROR] You are not login yet?
login: pass: - Signing in leetcode.com
[ERROR] invalid password?
login: pass: - Signing in leetcode.com
[ERROR] invalid password?
```

## Your Environment

- *OS*: Ubuntu 19.04
- *Installed extensions*:
  - C/C++
  - LeetCode
  - Settings Sync
  - Test Explorer UI
  - Vim
  - vscode-icons
- *extension version*: 0.14.1

**VS Code About**
Version: 1.33.1
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:20:22.771Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 5.0.0-13-generic

**Comment by jdneo** [comment] 2019-06-01 02:41
@AB1908 I tried a password which is `!@#$%^&*()` and can successfully signed in. Please make sure you are using the correct endpoint. The LeetCode and LeetCode-CN do not share the same account system.

**Comment by AB1908** [comment] 2019-06-01 02:46
I tried both endpoints.
________________________________

**Comment by jdneo** [comment] 2019-06-01 02:55
Hmmm, tried it again in Fedora but still cannot repro. If someone has any clue for this issue. Please feel free to let me know.

**Comment by Dh0le** [comment] 2019-11-26 14:52
I am having this problem as well. I tried several accounts in both endpoints but none of them can successfully login. I am pretty sure that the password is correct. But it kept telling me that it could be an invalid password.  VSC on the Windows system works well but this happened when I try to use it on mac os x.

**Comment by zentby** [comment] 2019-11-28 12:15
Mac +1. The leetcode-cn works well but the leetcode.com keeps failing

**Comment by klutzoder** [comment] 2019-11-28 16:02
Mac (10.15.1) +1. the leetcode.com keeps failing.

**Comment by zentby** [comment] 2019-11-28 22:24
> Mac (10.15.1) +1. the leetcode.com keeps failing.

Found another session is more useful #478

**Comment by zentby** [comment] 2019-11-28 22:24
Duplicate of #478

**Comment by AB1908** [comment] 2019-12-12 11:11
Have changed password and tried again. Same error.

**Comment by ubwzwd** [comment] 2020-01-15 01:45
I'm also having the same "invalide password?" trouble in Win10.

**Comment by jdneo** [comment] 2020-01-20 05:25
We cannot directly log in to `LeetCode US` now, Please check [here](https://github.com/jdneo/vscode-leetcode#%EF%B8%8F-attention-%EF%B8%8F--workaround-to-login-to-leetcode-endpoint) for details

If you cannot login to `LeetCode-CN` using password generated by KeePass, please let me know.

**Closed** 2020-02-03 06:00 UTC
Labels: help wanted, need more info
