### ISSUE TITLE
Failed to switch endpoint. Please open the output channel for details.

### ISSUE THREAD

**Issue by tjy-cool** [jdneo/vscode-leetcode#211] opened 2019-03-15 14:48 UTC
My pc is mac 10.13.6, node.js version: v11.7.0
And I want change the the end endpoint for Chinese by click the icon that like earth, but vscode pop up report error: Failed to switch endpoint. Please open the output channel for details.
and the command line shows: [ERROR] Plugin not found!
so I can't login my Chinese account, 
and I need help.

**Comment by sandove** [comment] 2019-03-15 14:54
Exactly the same problem...Need help...

**Comment by fgh1999** [comment] 2019-03-15 16:19
+1

**Comment by Sparkuggz** [comment] 2019-03-16 02:02
+1

**Comment by Vigilans** [comment] 2019-03-16 04:46
This bug has already been covered by the review discussion here:
https://github.com/jdneo/vscode-leetcode/pull/193#discussion_r265016833

The bugfix didn't get shipped in current version, and will be solved in another PR.

**Comment by RyanIPO** [comment] 2019-03-16 12:21
+1

**Comment by jdneo** [comment] 2019-03-16 12:27
@All Are you guys all see the error messages as: `[ERROR] Plugin not found`?

As a workaround, could you please try to remove `$HOME/.lc` and try it again and let me if this could help?

**Comment by tjy-cool** [comment] 2019-03-16 12:43
I remove the dir $HOME/.lc with the command: rm -rf ~/.lc
but it doesn't work, when I open vscode click the icon Leetcode can see the same error messages 
: [ERROR] Plugin not found?  
and change the endpoint can also the error message.

**Comment by tjy-cool** [comment] 2019-03-16 12:57
I use `tree` command in the dir ~/.lc, it shows : 
├── leetcode
│   └── cache
└── plugins.json
 
and I use command `cat plugins.json`  shows:
`{"solution.discuss":true,"company":true,"cache":true,"retry":true,"leetcode":true}`

I think it useful message for you to solve the bug.

**Comment by Vigilans** [comment] 2019-03-16 12:57
@tjy-cool The proper workaround is: 
1. Find your leetcode-cli binary path, or execute `npm install leetcode-cli -g` and use `leetcode`` command.
2. Execute `leetcode plugin -I leetcode.cn`.

Then the leetcode.cn plugin is found thereafter.

**Comment by tjy-cool** [comment] 2019-03-16 13:12
@Vigilans thanks
I have execute the command `cd ~/` `npm install leetcode-cli -g` and `leetcode` by order
but the command `leetcode` shows warnning:
`[WARN] Installing missing plugins, might take a while ...`

and I don't know how to flow the step 2

**Comment by tjy-cool** [comment] 2019-03-16 13:15
@Vigilans  thanks
I have execute the command cd ~/ npm install leetcode-cli -g and leetcode by order
but the command leetcode shows warning:
[WARN] Installing missing plugins, might take a while ...

and I don't know how to follow the step 2

**Comment by tjy-cool** [comment] 2019-03-16 13:17
@Vigilans  thanks
I have execute the command `cd ~/`  `npm install leetcode-cli -g` and `leetcode` by order
but the command leetcode shows warning first time:
`[WARN] Installing missing plugins, might take a while ...`
and the second time show nothing.

and I don't know how to follow the step 2

**Comment by Vigilans** [comment] 2019-03-16 13:21
@tjy-cool 
> use `leetcode` command.

This is mentioned in contrast with 

> Find your leetcode-cli binary path

Because if you choose the `Find your leetcode-cli binary path` choice, `<your-leetcode-bin>` is `<your root of npm>/npm_modules/leetcode-cli/bin/leetcode`, 

where as after executing `npm install leetcode-cli -g`, `<your-leetcode-bin>` is `leetcode`.

So for now, you can just execute `leetcode plugin -i leetcode.cn`.

**Comment by marshallseu** [comment] 2019-03-16 15:45
@Vigilans thanks a lot.

**Comment by RyanIPO** [comment] 2019-03-16 15:48
I don't know where the problem is. But when I reload it and Clean up related files .everything is ok.
👻 👻 👻

**Comment by fgh1999** [comment] 2019-03-17 05:17
Already fixed. Thanks a lot. @Vigilans

**Comment by jdneo** [comment] 2019-03-17 11:32
I'm closing this issue for now since this issue should be fixed with #212.

We will release the fix recently in `0.13.1`.

If you still have problems after using `0.13.1`, please feel free to let us know.

**Closed by jdneo** 2019-03-17 11:32 UTC
Labels: bug
