### ISSUE TITLE
New Question after i fix the error http 400

### ISSUE THREAD

**Issue by RenZMin** [jdneo/vscode-leetcode#493] opened 2019-12-09 02:42 UTC
Before you submit an question we recommend you to check out the [DOCUMENT](https://github.com/jdneo/vscode-leetcode/blob/master/README.md) first.

You can also find more information in:
- [TROUBLESHOOTING](https://github.com/jdneo/vscode-leetcode/wiki/Troubleshooting)
- [FAQ](https://github.com/jdneo/vscode-leetcode/wiki/FAQ)

## 💬 Questions and Help
Hello,i have fixed the http error 400 yesterday.But new problems comes too.
Red wavy lines are now always present when programming.Displays undefined identifiers.it didn't exist before. I'm not sure what went wrong.

![d89e5ccb414799f5b4fea1a68ae5118](https://user-images.githubusercontent.com/42882641/70403058-8cda5680-1a70-11ea-9a79-75e23fb9de13.png)

Thank you.
Please outline the questions.

**Comment by jdneo** [comment] 2019-12-09 03:07
The extension does not provide any intelliSense features, the problem should be caused by other extensions which you installed in your VS Code, i.e. C++ extension.

Close since out of scope.

**Closed by jdneo** 2019-12-09 03:07 UTC
