### ISSUE TITLE
There is no data provider registered that can provide view data.

### ISSUE THREAD

**Issue by sepetboy** [jdneo/vscode-leetcode#251] opened 2019-04-02 03:09 UTC
Version: 1.32.3 (user setup)
Chrome: 66.0.3359.181
Node.js: 10.2.0
OS: Windows_NT x64 10.0.17134

what is the reason for this

**Comment by Vigilans** [comment] 2019-04-02 03:48
Is there any output message if you press Ctrl+Shift+U and toggle the channel from Tasks or 任务 to LeetCode?

@jdneo I think after merging #249, the issue template should require and guide them to provide the leetcode channel output.

**Comment by jdneo** [comment] 2019-04-02 04:16
@Vigilans Mostly the error `There is no data provider registered that can provide view data` is caused because of the extension failed to activate, so there will be nothing in the output channel.

We have received a lot of that kind of errors, suspecting that this is due to installing the cli plugin when activating.

**Comment by Vigilans** [comment] 2019-04-02 05:28
So #249 is meant to bring something to output channel when failed to activate, which I think should help us diagnose the problems O`O

**Comment by jdneo** [comment] 2019-04-02 05:33
Oh, yes it is.

**Comment by sepetboy** [comment] 2019-04-02 06:21
> Is there any output message if you press Ctrl+Shift+U and toggle the channel from Tasks or 任务 to LeetCode?
> 
> @jdneo I think after merging #249, the issue template should require and guide them to provide the leetcode channel output.

The leetcode channel output is
[ERROR] Plugin not found!
- Downloading https://github.com/skygragon/leetcode-cli-plugins/raw/master/plugins/company.js
[ERROR] Error: connect ETIMEDOUT 13.250.177.223:443

**Comment by jdneo** [comment] 2019-04-02 06:56
@sepetboy Thank you for reporting the logs.

@Vigilans It seems that some users cannot download the plugin due to the network issue. Is it possible that we release the CLI with those plugins embedded? If that could be done. I think our extension could be much more stable and faster to activate.

**Comment by sepetboy** [comment] 2019-04-02 07:49
Maybe the network was restricted by my company,I guess I need some kind of permission.

**Comment by jdneo** [comment] 2019-04-02 13:20
The root cause looks duplicated with #240.

Closing it for now and let's track it in #240.

@sepetboy Thank you for reporting the issue to us.

**Closed by jdneo** 2019-04-02 13:20 UTC
Labels: bug

**Comment by Vigilans** [comment] 2019-04-02 13:25
> @Vigilans It seems that some users cannot download the plugin due to the network issue. Is it possible that we release the CLI with those plugins embedded? If that could be done. I think our extension could be much more stable and faster to activate.

Yes, I've tried to add the plugin manually to `lib/plugins` folder, and everything works fine. 

> @Vigilans #249 is merged. Would you mind to send another PR to update the issue templates and update the ACKNOWLEDGEMENT.md as well?

Sure.
