### ISSUE TITLE
problem of connect to leetcode

### ISSUE THREAD

**Issue by yjaal** [jdneo/vscode-leetcode#290] opened 2019-04-24 02:45 UTC
when i connect to leetcode or leetcode China with vscode, the output is  
Signing in leetcode.com
[ERROR] Error: connect ETIMEDOUT 47.99.228.218:443
you can find that everytime it connect to leetcode.com, it dosent connect to leetcode-cn.com
## 💬 Questions and Help

Please outline the questions.

**Comment by jdneo** [comment] 2019-04-24 04:39
@yjaal 

Are you behind a proxy? https://github.com/jdneo/vscode-leetcode/wiki/%E7%96%91%E9%9A%BE%E8%A7%A3%E7%AD%94#thinking-%E6%97%A0%E6%B3%95%E7%99%BB%E5%BD%95

**Comment by yjaal** [comment] 2019-04-26 01:10
no, perhaps is the problem of company network, i have succeed at home

**Comment by jdneo** [comment] 2019-04-26 01:27
@yjaal Thank you for the information. I'm closing this since it seems not a bug of the extension. Feel free to let me know if you have more questions.

**Closed by jdneo** 2019-04-26 01:27 UTC
