### ISSUE TITLE
define the part of code to submit

### ISSUE THREAD

**Issue by magic-akari** [jdneo/vscode-leetcode#418] opened 2019-09-15 14:31 UTC
## 🚀 Feature Proposal

We need a magic comment to define where is the actual user code to submit.

## Motivation

I am playing with rust. The code structure is as follow.

```rust
pub struct Solution;

impl Solution {
    pub fn two_sum(nums: Vec<i32>, target: i32) -> Vec<i32> {
    // ...
    }
}
```

look at the first line(Line 9).
I will get an error in vs code without that line.
And I will get an error if I submit code with that line.

```
✘ Compile Error
  ✘ 0/0 cases passed (N/A)
  ✘ Error: Line 54, Char 1: the name `Solution` is defined multiple times (solution.rs)
  ✘ Error: Line 54, Char 1: the name `Solution` is defined multiple times (solution.rs)
   |
9 | pub struct Solution {}
   | ------------------- previous definition of the type `Solution` here
...
54 | struct Solution;
   | ^^^^^^^^^^^^^^^^ `Solution` redefined here
   |
   = note: `Solution` must be defined only once in the type namespace of this module
```

The Line 54 is at LeetCode test side.

It is better to define which is the actual user code to submit and which is not.

---

For example:

```rust
pub struct Solution;

// @lc user code start

impl Solution {
    pub fn two_sum(nums: Vec<i32>, target: i32) -> Vec<i32> {
        unimplemented!()
    }
}

// @lc user code end

#[cfg(test)]
mod tests {
    use super::Solution;

    #[test]
    fn it_works() {
        assert_eq!(vec![1, 2], Solution::two_sum(vec![3, 2, 4], 6));
    }
}
```

```python
# @lc user code start


class Solution:
    def twoSum(self, nums: List[int], target: int) -> List[int]:
        pass

# @lc user code end


if __name__ == '__main__':
    s = Solution()
    print s.twoSum([3, 2, 4], 6)
```

**Comment by jdneo** [comment] 2019-09-16 01:44
So each time we will extract out the content between the special tag comments, save it to a temp file and submit through CLI.

Another usage for this tag to provide a better place to put the Code Lens (issue #407 ). Currently the Code Lens is always put at the end of the file. 

@magic-akari Would you like to contribute for this? I guess we need also update the template here: https://github.com/leetcode-tools/leetcode-cli/tree/master/templates

**Comment by magic-akari** [comment] 2019-09-16 06:55
I tried to make a prototype here https://github.com/leetcode-tools/leetcode-cli/pull/23
Would you like to review it?

**Comment by jdneo** [comment] 2019-09-16 11:41
Thanks, I just left some comments there.

**Comment by jasonsun0310** [comment] 2019-09-16 15:11
I have a python script that does it better. It does the following things:
1. generate a local runnable cpp file linked to my own header only cpp-stl pretty pretty printer. 
2. run it and test against the test cases.
3. also generate a submittable file without the main and all the includes. 


The most straight forward way to do this is to define a `runtests` functions inside the solution class and only call the runtests function inside the main.  Scripting becomes much easier. 

Let me know if you would like to make this a multi-language script. Right now what is missing is the ability to catch failed cases and convert it to appropriate types in the language. However, this is easily achievable if you are willing to use some Haskell or Ocaml to do pattern match!

**Comment by jdneo** [comment] 2019-09-30 05:21
Thank you @jasonsun0310 ,

So far the problem is addressed in https://github.com/leetcode-tools/leetcode-cli/pull/23.

Let's see if the users need more powerful support later...

**Closed by jdneo** 2019-09-30 05:21 UTC
Labels: enhancement
