### ISSUE TITLE
command 'leetcode.toggleLeetCodeCn' not found

### ISSUE THREAD

**Issue by yanite** [jdneo/vscode-leetcode#203] opened 2019-03-13 02:57 UTC
Environment

- *os*: windows 10
- *extension settings*:
- *nodejs version*: v11.11.0
- *vscode version*:  1.32.1
- *extension version*:  0.12.0

安装没问题点击面板上的一切都报这个错误

**Comment by jdneo** [comment] 2019-03-13 03:14
Please check the document here to see if it could help: https://github.com/jdneo/vscode-leetcode/wiki/%E7%96%91%E9%9A%BE%E8%A7%A3%E7%AD%94#thinking-%E6%8F%90%E7%A4%BA%E9%94%99%E8%AF%AF-command-leetcodexxx-not-found

**Comment by qianchanger** [comment] 2019-03-15 14:21
我也遇到了.

**Comment by qianchanger** [comment] 2019-03-15 14:24
I also have this problem......
- mac 10.13.4
- vscode 1.32.3
- nodejs v11.11.0
![image](https://user-images.githubusercontent.com/19400870/54438153-11fa3e80-4771-11e9-968d-a86dd030a9c2.png)

![image](https://user-images.githubusercontent.com/19400870/54438130-0575e600-4771-11e9-8119-6188474361f8.png)

**Comment by qianchanger** [comment] 2019-03-15 14:37
The above documentation does not seem to contain this problem

**Comment by qianchanger** [comment] 2019-03-15 14:50
switch this leetcode-plugin to 0.12 version , it works.   :)

**Comment by jdneo** [comment] 2019-03-16 11:40
Not sure if this is related to this issue: https://github.com/jdneo/vscode-leetcode/issues/201

For example, you are using a third-party bash, like `zshell`, and your node.js is only available in the `zshell`, not the default bash.

Then the extension will not run the leetcode command successfully since it will spawn a child process from the default bash.

**Comment by Yihemu** [comment] 2019-03-16 11:52
![image](https://user-images.githubusercontent.com/43208747/54474811-ae314d80-4824-11e9-85ab-5283e48e954a.png)
![image](https://user-images.githubusercontent.com/43208747/54474830-d7ea7480-4824-11e9-9a36-bd8d9c125f38.png) 
But i haven't used a third-party bash.

**Comment by jdneo** [comment] 2019-03-16 11:56
Have you tried this: https://github.com/jdneo/vscode-leetcode/wiki/%E7%96%91%E9%9A%BE%E8%A7%A3%E7%AD%94#thinking-%E6%8F%90%E7%A4%BA%E9%94%99%E8%AF%AF-command-leetcodexxx-not-found

**Comment by Yihemu** [comment] 2019-03-16 12:00
> Have you tried this: https://github.com/jdneo/vscode-leetcode/wiki/%E7%96%91%E9%9A%BE%E8%A7%A3%E7%AD%94#thinking-%E6%8F%90%E7%A4%BA%E9%94%99%E8%AF%AF-command-leetcodexxx-not-found

![image](https://user-images.githubusercontent.com/43208747/54474927-1d5b7180-4826-11e9-8750-92cae6ae9d6f.png)

**Comment by ybtuteng** [comment] 2019-03-17 03:35
today I met this error too
vscode:1.32.3
node:10.15.1
mac os:10.14.3
I use mac's terminal as default shell
yesterday everything is ok, and I have used it for a week normally
but today it cannot work suddenly
![image](https://user-images.githubusercontent.com/12271804/54484817-98656c00-48a8-11e9-8339-e571f8c1fc57.png)
![image](https://user-images.githubusercontent.com/12271804/54484819-a0bda700-48a8-11e9-828e-6cd08a612b40.png)

**Comment by jdneo** [comment] 2019-03-17 10:49
Emm, suspecting related with #211. We will release a release recently.

**Comment by jdneo** [comment] 2019-03-17 11:32
I'm closing this issue for now since this issue should be fixed with #212.

We will release the fix recently in `0.13.1`.

If you still have problems after using `0.13.1`, please feel free to let us know.

**Closed by jdneo** 2019-03-17 11:32 UTC
Labels: need more info

**Comment by com3345** [comment] 2019-03-30 06:41
Same problem..

+ os: win10 1803
+ vs code version: 1.32.3
+ node.js version: 10.15.3 
+ extension LeetCode version: 0.13.1
+ And I don't have any other bashes except default powershell/cmd.

I'm wondering if the proxy setting leads to the situation:

![image](https://user-images.githubusercontent.com/11958810/55272599-dd9e8a80-52f9-11e9-904d-fac124ad5692.png)

**Comment by jdneo** [comment] 2019-03-31 10:58
@Vigilans Any ideas?

**Comment by Vigilans** [comment] 2019-04-01 02:26
> But i haven't used a third-party bash.

@Yihemu why is the command _toogleLeetCodeCn_ Σ( ° △ °|||)︴?

It seems that this bug is caused by the failure of initialization in extension's main entry. 

Several reasons that may cause `activate`'s early exit:
* `leetCodeExecutor.meetRequirements` return false and `activate` exits directly.

  ```typescript
    if (!await leetCodeExecutor.meetRequirements()) {
        return;
    }
  ```
  There will be messages in the output channel if the bug is triggered for this reason. 
  @ALL Could you please provide the content by pressing `Ctrl+Shift+U` and toggle the channel from `Tasks` or `任务` to `LeetCode`?
* Some other exception is triggered in the rest part of initialization. It is a grief that the exception content won't get processed by `leetCodeChannel`.

@jdneo I think we may provide a `try ... catch` block in `activate`, and let `LeetCodeChannel` output the error message, at the same time showing a prompt saying `Extension initialization failed`, along with a button to guide them to the output channel?

**Comment by ShannonGu** [comment] 2019-04-04 08:27
I also encountered the problem, then I install the old version, and it works.

**Comment by jdneo** [comment] 2019-04-04 08:29
@ShannonGu Please try `0.13.3`

**Comment by ShannonGu** [comment] 2019-04-04 08:36
@jdneo um.....0.13.3 suddenly works. Thanks!

**Comment by HeronWan** [comment] 2019-08-29 09:56
I also encountered the problem

**Comment by WincentZhang** [comment] 2019-11-15 12:42
The same question, Oh  god! no way to finish?

**Comment by xuxinyang** [comment] 2020-08-14 03:12
Does someone fix it?

**Comment by xuxinyang** [comment] 2020-08-14 03:17
I just restart VScode some times, it's works!

**Comment by yhaoyan** [comment] 2020-09-29 01:00
> I'm closing this issue for now since this issue should be fixed with #212.
> 
> We will release the fix recently in `0.13.1`.
> 
> If you still have problems after using `0.13.1`, please feel free to let us know.

I use  v0.17.0 but meet the mistake again..
Please help

![image](https://user-images.githubusercontent.com/8141873/94500558-383bde00-0232-11eb-8096-3546309fb30d.png)

**Comment by coco8514** [comment] 2021-01-06 06:32
<img width="563" alt="Screen Shot 2021-01-05 at 10 32 08 PM" src="https://user-images.githubusercontent.com/55068185/103736846-df54b200-4fa5-11eb-8a1f-c64146e9dcce.png">

**Comment by zhongyangxun** [comment] 2021-01-29 02:42
It works on my Windows 10 machine by restarting VS Code.
