### ISSUE TITLE
双击题目，打开详情支持

### ISSUE THREAD

**Issue by greyireland** [jdneo/vscode-leetcode#138] opened 2019-02-19 05:31 UTC
右键显示问题太繁琐，希望可以优化一下

**Comment by jdneo** [comment] 2019-02-19 06:42
Thank you for your suggestion. While the problem is that VS Code has no API about the double click event in explorer.

Closing it for now. I'll keep watching the API will be available in the future.

**Closed by jdneo** 2019-02-19 06:42 UTC
