### ISSUE TITLE
Error: LeetCode extension needs Node.js installed in environment path

### ISSUE THREAD

**Issue by skyhiter** [jdneo/vscode-leetcode#201] opened 2019-03-12 09:26 UTC
## 🐛 Bug Report

When sign in, it pops up  "LeetCode extension needs Node.js installed in environment path".
But node command has been in my environment path.
![image](https://user-images.githubusercontent.com/3953193/54187833-5b385d00-44e9-11e9-9d66-a72947a23f05.png)

## To Reproduce

select "LeetCode Sign In" command.

## Expected behavior

pop up login window.

## Your Environment

- *os*: macbook pro, macOS 10.14.3
- *extension settings*: 
RalfZhang.filetemplate
SirTori.indenticator
aaron-bond.better-comments
abusaidm.html-snippets
alefragnani.project-manager
anseki.vscode-color
austin.code-gnu-global
christian-kohler.path-intellisense
CoenraadS.bracket-pair-colorizer
dbaeumer.vscode-eslint
donjayamanne.githistory
eamodio.gitlens
ecmel.vscode-html-css
eg2.tslint
emilast.LogFileHighlighter
felipecaputo.git-project-manager
formulahendry.auto-close-tag
formulahendry.code-runner
goessner.mdmath
GrapeCity.gc-excelviewer
HookyQR.beautify
humao.rest-client
humy2833.ftp-simple
James-Yu.latex-workshop
johnstoncode.svn-scm
kondratiev.sshextension
lextudio.restructuredtext
liximomo.sftp
lonefy.vscode-JS-CSS-HTML-formatter
MS-CEINTL.vscode-language-pack-zh-hans
ms-mssql.mssql
ms-python.anaconda-extension-pack
ms-python.python
ms-vscode.cpptools
ms-vscode.Go
neuron.neuron-IPE
octref.vetur
redhat.java
redhat.vscode-yaml
ritwickdey.LiveServer
robertohuertasm.vscode-icons
rust-lang.rust
ryu1kn.partial-diff
SBSnippets.pytorch-snippets
Shan.code-settings-sync
shengchen.vscode-leetcode
streetsidesoftware.code-spell-checker
VisualStudioExptTeam.vscodeintellicode
vscjava.vscode-java-debug
vscjava.vscode-java-dependency
vscjava.vscode-java-pack
vscjava.vscode-java-test
vscjava.vscode-maven
waderyan.gitblame
yzane.markdown-pdf
yzhang.markdown-all-in-one
zhuangtongfa.Material-theme
Zignd.html-css-class-completion
- *nodejs version*: v10.15.2
- *vscode version*: 1.32.1
- *extension version*: 0.12.0

**Comment by jdneo** [comment] 2019-03-12 11:54
@skyhiter How did you start your VS Code?

**Comment by skyhiter** [comment] 2019-03-13 04:05
Thank you for your prompt reply. 

I just clicked the vscode icon from mac's Dock.

In my impression，vscode 1.30(when I first use `leetcode` extension) was going well. But this error has arisen when vscode updated to 1.31.(the same to 1.32 ).

![image](https://user-images.githubusercontent.com/3953193/54252607-73aa8500-4586-11e9-8a21-2868611ce319.png)
![image](https://user-images.githubusercontent.com/3953193/54252810-3266a500-4587-11e9-85c9-83a9d2cc70f2.png)

**Comment by jdneo** [comment] 2019-03-13 04:35
@skyhiter Wired. It should not be a problem with the VS Code. 

Have you upgraded the node recently? Have you tried to restart the OS?

**Comment by skyhiter** [comment] 2019-03-13 05:41
I can't remember.But, I install node8, it not works.

1. brew uninstall node (v10)
2. brew install node@8
3. vim .zshrc,delete  `export PATH="/usr/local/opt/node@10/bin:$PATH"`,
 add `export PATH="/usr/local/opt/node@8/bin:$PATH"`
4. now, system zsh shell will show `v8.15.1`
5. resinstall vscode leetcode extension.
6. restart vscode, and LeetCode Sign In,  but it pops up this error also.
![image](https://user-images.githubusercontent.com/3953193/54256073-af991680-4595-11e9-9927-da4a99625c6a.png)

**Comment by jdneo** [comment] 2019-03-13 05:53
Guess this is because you are put the node executable into your zshell's path, but not the default bash's path.

While the extension won't able to get this information when it creates a child process to execute leetcode tasks.

**Comment by skyhiter** [comment] 2019-03-13 06:21
Maybe. I aways use zsh, it had worked before.

I'll find out the cause of the error by  myself.  Thank you for your prompt reply.

**Comment by skyhiter** [comment] 2019-03-13 06:31
please see issue[Customized environment variables not available for extensions when VS Code is not launched via terminal](https://github.com/Microsoft/vscode/issues/69728).

When I start vscode from zsh, it works!

**Comment by jdneo** [comment] 2019-03-13 06:53
In my personal opinion, I think it's not a bug. This is as expected for using another shell.

Closing it for now since the issue has been resolved.

**Closed by jdneo** 2019-03-13 06:53 UTC

**Comment by tianzhich** [comment] 2022-01-06 11:28
Any other way to resolve this except for launching vsc from terminal?

**Comment by daisy11100** [comment] 2022-01-10 02:47
I have the same problem,because input the error node path.so  try to get the correct node.exe path

**Comment by DineshRajanT** [comment] 2022-11-02 18:41
Have the same issue!!

**Comment by YeQiuO** [comment] 2023-04-26 14:13
这个问题恶心了我一个下午，总算是在睡前解决了

**具体解决方案：
在系统变量中找到PATH，点击编辑，点击新建，添加 C:\Windows\System32 这个变量，随即确定**

分析原因：
win使用了 where node 命令调用 node.exe，调用失败就会出现这个问题

如果有帮助到你，请祝我前程似锦~
当然，也祝你万事顺意！

**Comment by LeonardoRick** [comment] 2024-11-03 18:12
I have the same issue. In my opinion this is not expected even using another shells.

**Comment by santiweide** [comment] 2025-08-06 11:41
same on Mac....after system update. before it works

**Comment by Erik262** [comment] 2026-03-04 13:18
I’m facing the same issue. To resolve it, I found the node installation location by typing “which node” in terminal and then pasted the path into the LeetCode extension settings.
